version: "3.8"
services:
  web:
    build: .
    command: uvicorn app.main:app --reload
    volumes: 
      - .:/app
    ports:
      - 8000
    depends_on:
      - database
      - redis
  
  database:
    image: postgres:13.4-alpine
    ports: 
      - 5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db

  redis:
    image: redis:6.2.5-alpine
