version: "3.8"
services:
  web:
    build: ./
    command: uvicorn app.main:app --reload
    ports:
      - 8000
    depends_on:
      - database
      - redis
  
  database:
    image: postgres:13.4-alpine

  redis:
    image: redis:6.2.5-alpine
